[versions]
coroutines = "1.8.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-serialization = "1.6.2" # https://github.com/Kotlin/kotlinx.serialization/releases
mockito = "5.2.1" # https://github.com/mockito/mockito-kotlin/releases
moshi = "1.15.1" # https://github.com/square/moshi/blob/master/CHANGELOG.md
obsolete-json = "20240205" # https://github.com/stleary/JSON-java/releases
rxjava = "3.1.8" # https://github.com/ReactiveX/RxJava/releases
turbine = "1.0.0" # https://github.com/cashapp/turbine/releases

[libraries]
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
obsolete-json = { group = "org.json", name = "json", version.ref="obsolete-json" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.0.3" } # https://github.com/JLLeitschuh/ktlint-gradle/releases
