[versions]
coroutines = "1.6.4"
gson = "2.9.1"
kotlin = "1.7.10"
kotlinx-serialization = "1.4.0"
mockito = "4.0.0"
moshi = "1.14.0"
rxjava = "3.1.5"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
