[versions]
coroutines = "1.7.1" # https://github.com/Kotlin/kotlinx.coroutines/releases
gson = "2.10.1"
kotlin = "1.8.22"
kotlinx-serialization = "1.5.1"
mockito = "4.1.0"
moshi = "1.15.0"
rxjava = "3.1.6"
turbine = "0.13.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-rx3 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-rx3", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
mockito = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.0.0" }
